version: '3.5'

networks:
  internal: {}
  external: {}

volumes:
  caddy-data:
  grafana-data:
  prometheus-data:

services:
  minecraft-tavern:
    image: itzg/minecraft-server:java17-graalvm
    container_name: minecraft-tavern
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    networks:
      - external
    volumes:
      - ./config/minecraft/tavern/config:/config
      - ./config/minecraft/tavern/mods:/mods
      - ./data/minecraft/tavern:/data
    environment:
      MEMORY: "3G"
      JVM_OPTS: ""

      VERSION: 1.20.2
      TYPE: "FABRIC"
      REPLACE_ENV_VARIABLES: true
      REPLACE_ENV_DURING_SYNC: true

      CFG_MINECRAFT_DATAPACK_URL: ${MINECRAFT_DATAPACK_URL}
      CFG_MINECRAFT_RESOURCE_PACK_URL: ${MINECRAFT_RESOURCE_PACK_URL}
      CFG_MINECRAFT_RESOURCE_PACK_SHA1: ${MINECRAFT_RESOURCE_PACK_SHA1}
      CFG_MINECRAFT_ROOT_USER: ${MINECRAFT_ROOT_USER}

      EULA: true
      GUI: false
      MOTD: "That's what you get with a \\u00A7ccritical hit\\u00A7r!"
      ENABLE_WHITELIST: true

      ALLOW_FLIGHT: true
      ANNOUNCE_PLAYER_ACHIEVEMENTS: false
      DIFFICULTY: normal
      ENABLE_COMMAND_BLOCK: true
      ONLINE_MODE: true
      PVP: false
      SEED: -5132365962278556237
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 16

      WHITELIST: ${MINECRAFT_ROOT_USER}
      OPS: ${MINECRAFT_ROOT_USER}

      DATAPACKS: ${MINECRAFT_DATAPACK_URL}
      RESOURCE_PACK: ${MINECRAFT_RESOURCE_PACK_URL}

      MODRINTH_PROJECTS: |
        fabric-api:FhOnpSMY
        fabric-language-kotlin:vnTAITh8
        cloth-config:jvy82BGQ
        cristel-lib:HiLmugPC
        midnightlib:Ozm1zl15
        yacl:vede4iWJ
        c2me-fabric:ilKwGRiJ
        carpet:xksYKkvF
        ferrite-core:unerR5MN
        krypton:cQ60Ouax
        lazydfu:4SHylIO9
        lithium:qdzL5Hkg
        no-chat-reports:xQyq2W5g
        noisium:7p5BqRHp
        sneaky-server:lp8D0Lex
        starlight:PLbxwptm
        journeymap:7zt8duBI
        attack-through-grass:6B73MDT8
        axes-are-weapons:BDjHRAAE
        banner-flags:pQn2LUL0
        brewery:YItLjOD4
        calcmod:BDwPfWKe
        chunky:t8SbUchF
        convenient-mobgriefing:GYP5cKT7
        drops-into-shulker:CLO46UeR
        dynamic-lights:7cT5xqe9
        enchantment-decay:6fEOzo5e
        enchantment-lore:h5cyRqLy
        essential-commands:IuECGm2c
        eye-spy:1qkfVn85
        fallingtree:7PRbBpzE
        flame-sweeping:RA6JAR4X
        hyperleash:hB1EDCYo
        improved-signs:BfHDRKtd
        keep-some-inventory:7OKjECF7
        monsters-in-the-closet:XI1l9czA
        more-mobs:4ZQjIDUu
        netherite-beacons:SyQnSClE
        no-feeding-baby:XOAhLxDh
        powershot:Ssm0hBu1
        realisticsleep:iKynU94V
        ramel:2phry1w3
        saplanting:EO5ieVOe
        show-me-what-you-got:HXhkhLxu
        sit!:i9CXUeL3
        spawn-animations:dJbCLsdr
        tax-free-levels:KIjmjizn
        through-the-lily-pads-gently:pWQzvKBG
        unloaded-activity:hqwioCvS
        wandering-collector:4W5aZn8x
        where-is-it:where-is-it
        why-am-i-on-fire:xPOy7Kso
        worldedit:PTig47IL
        balm:qHXzOzUv
        forgiving-void:MPiNyFvE
        kleeslabs:XEBQ0HGG
        netherportalfix:5UbTkcSQ
        purpurpacks-axe-effective-skulls:XMhEhgiU
        purpurpack-axolotls-ignore-passives:BRkQlNxt
        purpurpack-blasting-smelts-glass:kg47l5Fp
        purpurpack-breed-axolotl-with-tropical-fish-item:mocBRxcj
        purpurpacks-chiseled-bookshelves-add-enchantment-power:AP4Yn7oh
        purpurpacks-copper-block-beacon-base:gQfLC53r
        purpurpacks-hoe-effective-cactus:E7r75rN0
        purpurpacks-hoe-effective-froglights:Ly6AXTCe
        purpurpacks-more-dyed-wool-and-carpet:3Qy6hoB8
        purpurpacks-one-step-dyed-shulker-boxes:iaw4ERNG
        purpurpacks-pickaxe-effective-glass:68mYt2Z3
        purpurpacks-pickaxe-effective-light-source-blocks:4wkzdXaF
        purpurpacks-pickaxe-effective-reinforced-deepslate:FUukXOJi
        purpurpacks-re-dye-concrete-powder:FJG4Taen
        purpurpacks-re-dye-glass:Q2dMMsU2
        purpurpacks-re-dye-terracotta:dW83mbTx
        purpurpacks-silk-touch-budding-amethyst:p31OQTic
        purpurpacks-silk-touch-reinforced-deepslate:TeGODzF6
        purpurpack-smelt-raw-ore-blocks:JGsyxycS
        purpurpacks-transparent-blocks-in-enchant-area:p9KRlNk5
        collective:Guw1MFbD
        bottle-your-xp:Ax5muOcA
        compact-help-command:MF3ZRv1n
        conduits-prevent-drowned:1XyB1iVm
        configurable-extra-mob-drops:oCrKqtL2
        crying-ghasts:mG5oBVp2
        cycle-paintings:xUu2hUCa
        dismount-entity:3VEbTHlN
        double-doors:PYWSGxBg
        dragon-drops-elytra:lybydPYY
        eroding-stone-entities:5DZWc4aN
        extended-bone-meal:deHYG7KH
        extract-poison:YurgGwZB
        fire-spread-tweaks:9Y5E6Xeq
        fish-on-the-line:LazFxAts
        followers-teleport-too:nFNnBMLh
        furnace-recycle:8Praefnr
        grabby-mobs:G4pIW4Vx
        grass-seeds:HGPm4PPz
        grindstone-sharper-tools:FDrI0UOV
        hand-over-your-items:aAhS4Ag9
        ice-prevents-crop-growth:K1IahI2M
        inventory-totem:9xhX1Apw
        just-mob-heads:KZDsRGFN
        keep-my-soil-tilled:DengqMwN
        mooshroom-spawn:6bJ53nEf
        move-boats:g7nbNgPd
        move-minecarts:Kj5FKo0P
        paper-books:BZ4Fvu1j
        random-shulker-colours:C0X8M5u4
        recast:9Saj7VJf
        respawning-shulkers:RvvtFjkV
        sleep-sooner:S3LAzoST
        smaller-nether-portals:VdLymA5v
        softer-hay-bales:gZfB1xMp
        spiders-produce-webs:c3e9qEny
        villager-death-messages:Fno2vfgD
        villager-names-serilum:WqNH3R93
        village-spawn-point:O3aJ4TG4
        weaker-spiderwebs:y64pimyg
        wool-tweaks:1bjyBBLW
        better-trees:LHuXoUsx
        ct-overhaul-village:7LYJgioY
        dungeons-and-taverns:JOwejnHw
        incendium:QL8CxhjY
        nullscape:w4mEZnbU
        towns-and-towers:avrYXbs7
        wwoo:cNiETBJi
    labels:
      traefik.tcp.routers.minecraft.rule: HostSNI(`tavern.${DUCKDNS_SUBDOMAIN}.duckdns.org`)
      traefik.tcp.routers.minecraft.tls: null
      traefik.tcp.services.minecraft.loadbalancer.server.port: 25565

  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: prometheus
    restart: unless-stopped
    depends_on:
      minecraft-tavern:
        condition: service_healthy
    networks:
      - internal
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana-oss:9.5.14
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
     - internal
    volumes:
      - grafana-data:/var/lib/grafana
    labels:
      traefik.http.routers.grafana.rule: Host(`grafana.${DUCKDNS_SUBDOMAIN}.duckdns.org`)
      traefik.http.services.grafana.loadbalancer.server.port: 3000

  traefik:
    image: traefik:v2.10.5
    container_name: traefik
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.domains[0].main=${DUCKDNS_SUBDOMAIN}.duckdns.org"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.${DUCKDNS_SUBDOMAIN}.duckdns.org"
      - "--certificatesresolvers.duckdnsResolver.acme.dnschallenge.provider=duckdns"
    depends_on:
      - minecraft-tavern
      - grafana
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "8080:8080"
    networks:
      - internal
      - external
    volumes:
      - caddy-data:/data
      - ./config/caddy:/config
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      DUCKDNS_TOKEN: ${DUCKDNS_TOKEN}

  duckdns:
    image: linuxserver/duckdns:version-e48542ca
    container_name: duckdns
    restart: unless-stopped
    networks:
      - internal
    environment:
      SUBDOMAINS: ${DUCKDNS_SUBDOMAIN}
      TOKEN: ${DUCKDNS_TOKEN}
      UPDATE_IP: ${DUCKDNS_UPDATE_IP}
