[metrics]
	#Exports amount of currently online players on your server
	enablePlayerCount = true
	#Exports amount of currently loaded entities on your server
	enableEntityCount = true
	#Internal to update gauge metrics in milliseconds (1 second = 1000 milliseconds)
	updateInterval = 1000
	#Should default Hotspot exports be registered?
	exportJvmMetrics = true
	#Exports amount of total loaded chunks on server
	enableTotalLoadedChunks = true
	#Exports count of handshake requests
	enableHandshakeCount = true
	#Exports count of milliseconds per tick (MSPT)
	enableMspt = true
	#On which port Prometheus webserver should be started?
	serverPort = 25585
	#Exports amount of currently loaded chunks on server
	enableLoadedChunks = true
	#Exports count of ticks per second (TPS)
	enableTps = true
[proxy]
	#HACK
	onlineMode = false
	#The message that gets show when the client is not allowed to connect to the server directly.
	disconnectMessage = "This server requires you to connect with Velocity."
	#Examples: text:<secret> env:FORWARDING_SECRET file:forwarding.secret
	forwardingSecret = "text:eOCiFPANsZFw"
	#This the Velocity proxy should be enabled.
	enable = true
	#HACK
	earlySend = false
	#HACK
	messageChain = false
